---
title: "Ran Hassin Data - Heterogeneity"
author: "Katherine Zee"
date: "January 27, 2017"
output: html_notebook
---

```{r }
library(nlme)
library(lme4)
library(ggplot2)
library(lmerTest)
theme_set(theme_bw(base_size = 14))
#For Bayesian analysis:
library(brms)

#For dotplots
library(Rcmdr)



```

## Ran PNAS Study 6
```{r}
setwd("/Users/zeekatherine/KZNB/Ran Data")
setwd("C:/Users/Niall/Dropbox/NIALL1/MET/Suppes Talk/Heterogeneity")

ran6a <- read.csv("exp6_all_data_long.csv")
ran6 <- subset(ran6a, exclude_from_analysis == "FALSE" & operand == "S")

ran6$presentation_time_f <- as.factor(ran6$presentation_time)

ran6$congr <- ifelse(ran6$congruent == "no", -.5, .5)
ran6$ptimer <- ifelse(ran6$presentation_time == "1700", -.5, .5)


## random intercept only
# MLE model
ran6mod1 <- lmer(rt ~ congr*ptimer + (1 | subject), data = ran6)
summary(ran6mod1)
confint(ran6mod1, oldNames = FALSE)



# Bayesian model
ran6mod1b <- brm(rt ~ congr*ptimer + (1 | subject), data = ran6, 
                 cores = 1, chains = 1)
summary(ran6mod1b)
WAIC(ran6mod1b)


## random slopes
# MLE model
ran6mod2 <- lmer(rt ~ congr*ptimer + (1 + congr | subject), data = ran6)
summary(ran6mod2)
confint(ran6mod2, oldNames = FALSE)

# Bayesian model
ran6mod2b <- brm(rt ~ congr*ptimer + (1 + congr | subject), data = ran6,
                 cores = 4, chains = 6, iter = 4000)
summary(ran6mod2b)
WAIC(ran6mod2b)
WAIC(ran6mod1b, ran6mod2b)

# Extracts all samples from the posterior
post.ran6mod2b<-posterior.samples(ran6mod2b)
hist(post.ran6mod2b$sd_subject_congr, breaks=50)
median(post.ran6mod2b$sd_subject_congr)


# Study 6 Dotplot (MLE model with random slopes)
summary(ran6mod2)
ran6mod2ranef <- -15.358 + ranef(ran6mod2)$subject[2]
quantile(ran6mod2ranef$congr, probs=c(.025, .5, .975))

#pdf("random_ran6_dotplot.pdf", width = 16, height = 8) 
stripchart(ran6mod2ranef, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-20, -9), xlab="Difference in Reaction Times between Congruent and Incongruent Conditions", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-18.6, -15.14, -12.21), col = c("red", "black", "red"),
       lwd = 3)
#dev.off()

```

## Ran PNAS Study 7
```{r}
setwd("/Users/zeekatherine/KZNB/Ran Data")
ran7a <- read.csv("exp7_all_data_long.csv")
ran7 <- subset(ran7a, subjective == "1" & operation == "S" & objective.test.score <= 0.6)
# COMPUTE filter_$=(subjective = 1 & OTRate <= 0.6 & operation = 'S').

ran7$congr <- ifelse(ran7$congruent == "no", -.5, .5)
ran7$ptimer <- ifelse(ran7$presentation.duration == "1000", -.5, .5)


## random intercept only
# MLE model
ran7mod1 <- lmer(rt ~ congr*ptimer + (1 | subject), data = ran7)
summary(ran7mod1)
confint(ran7mod1, oldNames = FALSE)


# Bayesian model
ran7mod1b <- brm(rt ~ congr*ptimer + (1 | subject), data = ran7, 
                 cores = 4, chains = 3)
summary(ran7mod1b)
WAIC(ran7mod1b)


## random slopes 
# MLE model
ran7mod2 <- lmer(rt ~ congr*ptimer + (1 + congr | subject), data = ran7)
summary(ran7mod2)
confint(ran7mod2, oldNames = FALSE)

# Bayesian model
ran7mod2b <- brm(rt ~ congr*ptimer + (1 + congr | subject), data = ran7,
                 cores = 4, chains = 6, iter = 4000)
summary(ran7mod2b)

WAIC(ran7mod2b)
WAIC(ran7mod1b, ran7mod2b)

# Extracts all samples from the posterior
post.ran7mod2b<-posterior.samples(ran7mod2b)
hist(post.ran7mod2b$sd_subject_congr, breaks=50)
median(post.ran7mod2b$sd_subject_congr)


# Study 7 Dotplot (MLE model with random slopes)
summary(ran7mod2)
ran7mod2ranef <- -13.496 + ranef(ran7mod2)$subject[2]
quantile(ran7mod2ranef$congr, probs=c(.025, .5, .975))

#pdf("random_ran7_dotplot.pdf", width = 16, height = 8) 
stripchart(ran7mod2ranef, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-30, 5), xlab="Difference in Reaction Times between Congruent and Incongruent Conditions", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-24.64, -14.14, -3.16), col = c("red", "black", "red"),
       lwd = 3)
#dev.off()





s7plusmath <- dplyr::full_join(ran7, s7math, by = "subject")

s7plusmath$math_anxiety.c <- scale(s7plusmath$math_anxiety, center=T, scale=F)

ran7mod2withmath <- lmer(rt ~ congr*ptimer + math_anxiety + (1 + congr | subject), data = s7plusmath)
summary(ran7mod2withmath)



ran7mod2int<- lmer(rt ~ congr*math_anxiety.c*ptimer + (1 + congr | subject), data = s7plusmath)
summary(ran7mod2int)
```


## Data from "DataPreProcessed.csv" file
```{r}
randata <- read.csv("DataPreProcessed.csv")

randata$val <- ifelse(randata$Valance==-1, -.5, .5)

randata$item <- randata$ItemNumber - 1
# Is this the trial number (time) or the stimulus??

## random intercept only
# MLE model
modelint <- lmer(RT ~ val + (1 | SubjectNumber), data = randata)
summary(modelint)
confint(modelint, oldNames=FALSE)


# Bayesian model
modelintb <- brm(RT ~ val + (1 | SubjectNumber), data = randata,
                 chains = 3, cores=4)
summary(modelintb)
WAIC(modelintb)



## random intercept and slope
# MLE model
modelslope <- lmer(RT ~ val + (val | SubjectNumber) + (1 | item), data = randata)
summary(modelslope)
confint(modelint, oldNames=FALSE)

# Bayesian model
modelslopeb <- brm(RT ~ val + (val | SubjectNumber), data = randata,
                   chains = 3, cores = 4)
summary(modelslopeb)
WAIC(modelintb, modelslopeb)

# Extracts all samples from the posterior
post.modelslopeb<-posterior_samples(modelslopeb)
hist(post.modelslopeb$sd_SubjectNumber__val, breaks=50)
median(post.modelslopeb$sd_SubjectNumber__val)

#Get predicted values based on randint only
predintonly<-predict(modelslopeb, re_formula = ~ (1 | SubjectNumber))
randata$RTpred<-predintonly[,1] + rnorm(length(predintonly))

modpredint <- brm(RTpred ~ val + (val | SubjectNumber), data = randata,
                   chains = 6, cores = 4, iter = 4000)
summary(modpredint)
WAIC(modpredint)

# Extracts all samples from the posterior
post.modpredint<-posterior_samples(modpredint)
hist(post.modpredint$sd_SubjectNumber__val, breaks=50)

median(post.modpredint$sd_SubjectNumber_val)

#### dot plot #####
summary(modelslope)
modelsloperanef <- 0.07413 + ranef(modelslope)$SubjectNumber[,2]
quantile(modelsloperanef$val, probs=c(.025, .5, .975))

pdf("random_randata_dotplot.pdf", width = 16, height = 8) 
stripchart(modelsloperanef, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-.03, .30), xlab="Difference in Reaction Times as a Function of Valence", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-.02, .05, .26), col = c("red", "black", "red"),
       lwd = 3)
dev.off()




# bayesian random effects:
summary(modelslopeb)
bm.modelsloperanef <- 0.07 + ranef(modelslopeb)$SubjectNumber[,2]
quantile(bm.modelsloperanef, probs=c(.025, .5, .975))

#### dot plot with MLE and Bayesian REs #####
x <- list("MLE"=modelsloperanef, "Bayes"=bm.modelsloperanef)

pdf("random_randata_dotplot2.pdf", width = 16, height = 8) 
stripchart(x,
 main="Multiple stripchart for comparision \n Gray = Mean and SDs, Colored Lines = Quantiles",
 xlab="Random Effects of Valence on RT",
 ylab="Method",
 col=c("red","blue"),
 pch=16,
 cex = 2, 
 cex.axis = 1.5, 
 cex.lab = 1.5,
 xlim=c(-.10, .30)
 )
abline(v=c(-.02, .05, .26), col = c("darkred", "darkred", "darkred"),
       lty = c("dashed", "solid", "dashed"), lwd = 4)
abline(v=c(.0006, .054, .23), col = c("darkblue", "darkblue", "darkblue"),
       lty = c("dashed", "solid", "dashed"), lwd = 4)
abline(v=c(-.09, .074, .24), col = c("darkgray", "darkgray", "darkgray"),
       lty = c("dashed", "solid", "dashed"), lwd = 4)
dev.off()




##### More graphs#####
plot(modelslopeb, pars = NA, parameters = NA, combo = c("dens",
  "trace"), N = 5, exact_match = FALSE, theme = NULL, plot = TRUE,
  ask = F, newpage = TRUE, device = NULL)
```


# With Math Variables Predicting Random Effects (updated 170316 KZ)
```{r}

setwd("~/KZNB")
# reading in Math Anxiety Variables
ran7math <- read.csv("Exp 7 math and motivation 13.2.2017.csv")

# merging with original ran7 data set:
ran7m <- merge(ran7, ran7math, by = "subject")

ran7m$math_anxiety.c <- scale(ran7m$math_anxiety, center=T, scale=F)
ran7m$math_self_rating.c <- scale(ran7m$math_self_rating, center=T, scale=F)

ran7mod2math <- lmer(rt ~ congr*ptimer + congr*math_anxiety.c + (1 + congr | subject), data = ran7m)
summary(ran7mod2math)
# SD of congr effect is 13.37. Basically the same as the model without the moderator (SD = 13.30)


# Dot plot with new random effects--i.e., shows how heterogeneity of the congruence effect changes when adding math anxiety was moderator
summary(ran7mod2math)
mathmodelranef <- -13.899 + ranef(ran7mod2math)$subject[,2]
quantile(mathmodelranef, probs=c(.025, .5, .975))

pdf("random_randata_mathanxiety_dotplot.pdf", width = 16, height = 8) 
stripchart(mathmodelranef, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-30, 5), xlab="Difference in Reaction Times as a Function of Congruence", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-24, -13, -5.37), col = c("red", "black", "red"),lwd = 3)
dev.off()


#### with "math_self_rating" variable as moderator:
ran7mod2math2 <- lmer(rt ~ congr*ptimer + congr*math_self_rating.c + (1 + congr | subject), data = ran7m)
summary(ran7mod2math2)
# size of random slope increases slightly







###### Old analyses with Math Anxiety (Ignore)
s7res1 <- ranef(ran7mod2)
s7res <- data.frame(as.numeric(rownames(s7res1$subject)),
                    s7res1$subject)
colnames(s7res)[1]="subject"
s7res$intercept <- s7res$X.Intercept.
View(s7res)

library(dplyr)

s7math <- read.csv("/Users/zeekatherine/KZNB/Ran Data/Exp 7 math and motivation 13.2.2017.csv")

s7math2 <- dplyr::full_join(s7res, s7math, by = "subject")
View(s7math2)

#write.csv(s7math2, file = "s7_mathvars_randomeffects.csv")

# Bi-variate correlations between math variables and random effects

cor.test(s7math2$psychometric, s7math2$congr) # not correlated
cor.test(s7math2$psychometric, s7math2$intercept) # weak neg correlation (not significant)

cor.test(s7math2$math_anxiety, s7math2$congr) # weak marginal correlation
cor.test(s7math2$math_anxiety, s7math2$intercept) # weak marginal correlation


# Correlation between intercepts and slopes = .37 (bigger than covariance estimate from the model?)
cor.test(s7math2$intercept, s7math2$congr) 


cor.test(s7math2$math_self_rating, s7math2$congr) # weak nonsig correlation
cor.test(s7math2$math_self_rating, s7math2$intercept) # weak nonsig

cor.test(s7math2$math_anxiety, s7math2$math_self_rating) # weak marginal correlation



mathvarsmod <- lm(congr ~ math_anxiety, data = s7math2)
summary(mathvarsmod)
```


### With More Data from Ran
```{r}
setwd("~/KZNB/Ran Data")

### With the face orientation dataset
ranface <- read.csv("experiment7_facesorient.csv")


ranface$fo1 <- ifelse(ranface$Face_orientation == 1, 1, 0)
ranface$fo2 <- ifelse(ranface$Face_orientation == 2, 1, 0)
ranface$trial.r <- ranface$trial -1

library(lme4)
library(lmerTest)

ranfacem1 <- lmer(RT ~ fo1 + fo2 + trial.r + (fo1 + fo2 | Participant), data = ranface)
summary(ranfacem1)
ranfacem1.re <- (ranef(ranfacem1)$Participant[2]) + -5.091e-01



ranfaceplot <- ggplot(data=ranface, aes(x=fo1, y=RT)) +
  geom_jitter(aes(color=as.factor(fo1)), position = position_jitter(width = .2), size=1.5) +
  labs(title = "RT by Face Orientation", x="id", y="RT") +
  stat_summary(aes(group=fo1), fun.y = mean, geom="point", colour="black", size=2) +
  stat_summary(fun.data=mean_cl_boot, geom='errorbar', size = .5) +
  scale_color_manual(values=c("orangered3", "green4")) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position='none',
        plot.title = element_text(lineheight=.8, face="bold"),
        axis.title.y = element_text(face="bold", vjust=0.5),
        axis.title.x = element_text(face="bold", vjust=-0.35)) +
  facet_wrap(~Participant) 
ranfaceplot
ggsave(ranfaceplot, file = "ranfaceplot.pdf")

# Dotplot 
ranfacem1.re <- as.vector((ranfacem1.re))
quantile(ranfacem1.re[,1], probs=c(.025, .5, .975))

#pdf("random_face_dotplot.pdf", width = 16, height = 8) 
stripchart(ranfacem1.re, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-1.2, .15), xlab="Individual Slopes in RT to Face Orientation", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-1.06, -0.5091, .01), col = c("red", "black", "red"),
       lwd = 3)
#dev.off()



### With the emotion dataset
setwd("~/KZNB/Ran Data")
ranem <- read.csv("exp1_expressions.csv")

ranem$emo1 <- ifelse(ranem$emotion ==1 , 1, 0)
ranem$emo2 <- ifelse(ranem$emotion ==2 , 1, 0)
ranem$trial.r <- ranem$Trial-1

ranemm1 <- lmer(RT ~ emo1 + emo2 + trial.r + (emo1 + emo2 | Subj), data = ranem)
summary(ranemm1)
# bigger RE for emo2 variable
ranemm1.re <- (ranef(ranemm1)$Subj["emo2"]) + -439.80029 


ranemplot <- ggplot(data=ranem, aes(x=emo2, y=RT)) +
  geom_jitter(aes(color=as.factor(emo2)), position = position_jitter(width = .2), size=1.5) +
  labs(title = "RT by Emotion", x="id", y="RT") +
  stat_summary(aes(group=emo2), fun.y = mean, geom="point", colour="black", size=2) +
  stat_summary(fun.data=mean_cl_boot, geom='errorbar', size = .5) +
  scale_color_manual(values=c("orangered3", "green4")) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position='none',
        plot.title = element_text(lineheight=.8, face="bold"),
        axis.title.y = element_text(face="bold", vjust=0.5),
        axis.title.x = element_text(face="bold", vjust=-0.35)) +
  facet_wrap(~Subj) 
ranemplot
#ggsave(ranemplot, file ="ranemplot.pdf")


# Dotplot 
quantile(ranemm1.re[,1], probs=c(.025, .5, .975))

#pdf("random_emotion_dotplot.pdf", width = 16, height = 8) 
stripchart(ranemm1.re, pch=21, bg="skyblue", cex=2, lwd=2,
           xlim=c(-880, 0), xlab="Individual Slopes in RT to Emotion", cex.axis=1.5, cex.lab=1.5)
abline(v=c(-826.84186, -439.80029, -81.19836 ), col = c("red", "black", "red"),
       lwd = 3)
#dev.off()

```

