* Encoding: UTF-8.
DATASET NAME DataSet4 WINDOW=FRONT.

MIXED rt WITH emo1 emo2
  /FIXED=emo1 emo2 | SSTYPE(3)
   /CRITERIA=CIN(95) MXITER(100) MXSTEP(40) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, 
    ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)
 /METHOD=REML
  /PRINT=TESTCOV G  SOLUTION TESTCOV 
  /RANDOM=INTERCEPT emo1 emo2 | SUBJECT(subj) COVTYPE(UN).
* /REPEATED=time | SUBJECT(id) COVTYPE(AR1).
