* Encoding: UTF-8.
DATASET NAME DataSet5 WINDOW=FRONT.

MIXED rt WITH fo1 fo2
  /FIXED=fo1 fo2 | SSTYPE(3)
   /CRITERIA=CIN(95) MXITER(100) MXSTEP(50) SCORING(1) SINGULAR(0.000000000001) HCONVERGE(0, 
    ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE)
 /METHOD=REML
  /PRINT=TESTCOV G  SOLUTION TESTCOV 
  /RANDOM=INTERCEPT fo1 fo2 | SUBJECT(participant) COVTYPE(UN).
 * /REPEATED=time | SUBJECT(id) COVTYPE(AR1).
